<?php

namespace App\DataFixtures;

use App\Entity\Account;
use App\Entity\Client;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AccountFixture extends Fixture
{
    private const ACCOUNTS = [
        'Wilhelm Conrad Röntgen' => ['EUR', 'USD', 'AUD', 'GBP'],
        'Hendrik Antoon Lorentz' => ['GBP'],
        'Pieter Zeeman' => [],
        'Henri Becquerel' => ['EUR', 'USD', 'AUD', 'GBP'],
        'Marie Curie' => [],
        'Pierre Curie' => ['EUR', 'USD', 'AUD'],
        'Lord Rayleigh' => ['EUR', 'USD', 'AUD', 'GBP'],
        'Philipp Lenard' => ['EUR', 'USD', 'AUD'],
        'Sir J.J. Thomson' => ['EUR'],
        'A.A. Michelson' => ['EUR', 'USD'],
        'Gabriel Lippmann' => ['EUR', 'USD', 'AUD', 'GBP'],
        'Ferdinand Braun' => ['EUR', 'USD', 'AUD'],
        'Guglielmo Marconi' => ['EUR', 'USD', 'AUD', 'GBP'],
        'Johannes Diederik van der Waals' => ['EUR', 'USD', 'AUD'],
        'Wilhelm Wien' => ['EUR', 'USD', 'AUD', 'GBP'],
        'Nils Dalén' => ['EUR', 'USD'],
        'Heike Kamerlingh Onnes' => ['EUR', 'USD', 'AUD'],
        'Max von Laue' => ['EUR', 'USD', 'AUD'],
        'Sir Lawrence Bragg' => ['EUR', 'USD', 'AUD', 'GBP'],
        'Sir William Bragg' => ['EUR', 'USD', 'AUD'],
        'Charles Glover Barkla' => ['EUR', 'USD', 'AUD'],
        'Max Planck' => ['EUR', 'USD', 'AUD'],
        'Johannes Stark' => ['EUR', 'USD', 'AUD', 'GBP'],
        'Charles Édouard' => [],
        'Albert Einstein' => ['EUR', 'USD', 'AUD', 'GBP'],
        'Niels Bohr' => ['EUR', 'USD', 'AUD'],
        'Robert Andrews' => ['EUR', 'USD', 'AUD'],
        'Karl Manne Georg Siegbahn' => ['EUR', 'USD', 'AUD'],
        'James Franck' => ['EUR', 'USD'],
        'Gustav Hertz' => ['EUR', 'USD', 'AUD'],
        'Jean Perrin' => ['EUR', 'USD', 'AUD', 'GBP'],
        'Arthur Holly Compton' => ['EUR', 'USD', 'AUD', 'GBP'],
        'C.T.R. Wilson' => ['EUR', 'USD', 'AUD'],
        'Sir Owen Willans Richardson' => ['EUR', 'USD', 'GBP', 'AUD'],
        'Louis de Broglie' => ['EUR', 'USD', 'AUD'],
        'Sir Chandrasekhara Venkata Raman' => ['EUR', 'RUR', 'USD', 'AUD', 'GBP'],
        'Werner Heisenberg' => ['EUR', 'USD', 'AUD'],
        'P.A.M. Dirac' => ['EUR', 'USD', 'AUD'],
        'Erwin Schrödinger' => ['EUR', 'USD', 'GBP'],
        'Sir James Chadwick' => ['EUR', 'USD', 'GBP'],
        'Carl David Anderson' => ['EUR'],
        'Victor Francis Hess' => ['USD'],
        'Clinton Joseph Davisson' => ['EUR', 'USD', 'RUR', 'AUD'],
        'Sir George Paget Thomson' => ['EUR', 'USD', 'AUD'],
        'Enrico Fermi' => ['EUR', 'USD', 'AUD'],
        'Ernest Orlando' => ['EUR', 'USD', 'AUD'],
        'Otto Stern' => ['EUR', 'USD', 'AUD'],
        'Isidor Isaac Rabi' => ['EUR', 'USD', 'AUD'],
        'Wolfgang Pauli' => ['EUR', 'USD', 'AUD'],
        'Percy Williams Bridgman' => ['EUR', 'USD', 'GBP'],
        'Sir Edward Victor Appleton' => ['EUR', 'USD', 'AUD'],
        'Patrick M.S. Blackett' => ['EUR', 'USD', 'AUD'],
        'Yukawa Hideki' => ['EUR', 'USD', 'AUD'],
        'Cecil Frank Powell' => ['EUR', 'USD', 'AUD'],
        'Sir John Douglas Cockcroft' => ['EUR', 'USD', 'AUD'],
        'Ernest Thomas Sinton Walton' => ['GBP', 'USD', 'AUD'],
        'Felix Bloch' => ['EUR', 'USD', 'RUR', 'AUD'],
        'E.M. Purcell' => ['EUR', 'USD', 'GBP'],
        'Frits Zernike' => ['EUR', 'USD', 'AUD'],
        'Max Born' => ['EUR', 'USD', 'AUD'],
        'Walther Bothe' => ['EUR', 'GBP', 'AUD'],
        'Polykarp Kusch' => ['EUR', 'USD', 'AUD'],
        'Willis Eugene Lamb, Jr.' => ['EUR', 'USD', 'AUD'],
        'John Bardeen' => ['EUR', 'USD', 'GBP'],
        'Walter H. Brattain' => ['EUR', 'USD', 'AUD'],
        'William B. Shockley' => ['EUR', 'USD', 'GBP'],
        'Tsung-Dao Lee' => ['EUR', 'USD', 'AUD'],
        'Chen Ning Yang	China' => ['EUR', 'USD', 'AUD'],
        'Pavel Alekseyevich Cherenkov' => ['EUR', 'USD', 'AUD'],
        'Ilya Mikhaylovich Frank' => ['EUR', 'USD', 'RUR', 'AUD'],
        'Igor Yevgenyevich Tamm' => ['EUR', 'USD', 'GBP'],
        'Owen Chamberlain' => ['EUR', 'USD', 'AUD'],
        'Emilio Segrè' => ['EUR', 'USD', 'AUD'],
        'Donald A. Glaser' => ['EUR', 'USD', 'AUD'],
        'Robert Hofstadter' => ['EUR', 'USD', 'AUD'],
        'Rudolf Ludwig Mössbauer' => ['EUR', 'USD', 'AUD'],
        'Lev Davidovich Landau' => ['EUR', 'USD', 'AUD'],
        'J. Hans D. Jensen' => ['EUR', 'USD', 'AUD'],
        'Maria Goeppert Mayer' => ['EUR', 'USD', 'GBP'],
        'Eugene Paul Wigner' => ['EUR', 'USD', 'AUD'],
        'Nikolay Gennadiyevich Basov' => ['EUR', 'USD', 'RUR', 'AUD'],
        'Aleksandr Mikhaylovich Prokhorov' => ['EUR', 'USD', 'GBP'],
        'Charles Hard Townes' => ['EUR', 'USD', 'AUD'],
        'Richard P. Feynman' => ['EUR', 'USD', 'AUD'],
        'Julian Seymour Schwinger' => ['EUR', 'USD', 'AUD'],
        'Tomonaga Shin\'ichiro' => ['EUR', 'USD', 'AUD'],
        'Alfred Kastler' => ['EUR', 'USD', 'AUD'],
        'Hans Albrecht Bethe' => ['EUR', 'RUR', 'USD', 'GBP'],
        'Luis W. Alvarez' => ['EUR', 'USD', 'AUD'],
        'Murray Gell-Mann' => ['EUR', 'USD', 'GBP'],
        'Hannes Alfvén' => ['EUR', 'USD', 'AUD'],
        'Louis-Eugène-Félix Néel' => ['EUR', 'USD', 'AUD'],
        'Dennis Gabor' => ['EUR', 'USD', 'AUD'],
        'Leon N. Cooper' => ['EUR', 'RUR', 'USD', 'AUD'],
        'John Robert Schrieffer' => ['EUR', 'USD', 'AUD'],
        'Leo Esaki' => ['EUR', 'USD', 'AUD'],
        'Ivar Giaever' => ['EUR', 'USD', 'AUD'],
        'Brian D. Josephson' => ['EUR', 'USD', 'GBP'],
        'Antony Hewish' => ['EUR', 'USD', 'AUD'],
        'Sir Martin Ryle' => ['EUR', 'USD', 'AUD'],
        'Aage N. Bohr' => ['EUR', 'USD', 'AUD'],
        'Ben R. Mottelson' => ['EUR', 'USD', 'AUD'],
        'James Rainwater' => ['EUR', 'USD', 'AUD', 'RUR'],
        'Burton Richter' => ['EUR', 'USD', 'AUD'],
        'Samuel C.C. Ting' => ['EUR', 'USD', 'AUD'],
        'Philip W. Anderson' => ['EUR', 'USD', 'AUD'],
        'Sir Nevill F. Mott' => ['EUR', 'USD', 'GBP'],
        'John H. Van Vleck' => ['EUR', 'USD', 'AUD'],
        'Pyotr Leonidovich Kapitsa' => ['EUR', 'USD', 'AUD', 'RUR'],
        'Arno Penzias' => ['EUR', 'USD', 'AUD'],
        'Robert Woodrow Wilson' => ['EUR', 'USD', 'AUD'],
        'Sheldon Lee Glashow' => ['GBP', 'USD', 'AUD'],
        'Abdus Salam' => ['EUR', 'USD', 'AUD'],
        'Steven Weinberg' => ['EUR', 'USD', 'GBP'],
        'James Watson Cronin' => ['EUR', 'USD', 'AUD', 'RUR'],
        'Val Logsdon Fitch' => ['EUR', 'USD', 'GBP'],
        'Nicolaas Bloembergen' => ['EUR', 'GBP', 'AUD'],
        'Arthur Leonard Schawlow' => ['EUR', 'USD', 'AUD'],
        'Kai Manne Börje Siegbahn' => ['EUR', 'USD', 'AUD'],
        'Kenneth Geddes Wilson' => ['EUR', 'USD', 'AUD'],
        'Subrahmanyan Chandrasekhar' => ['EUR', 'GBP', 'AUD'],
        'William A. Fowler' => ['EUR', 'USD', 'AUD'],
        'Simon van der Meer' => ['EUR', 'USD', 'AUD'],
        'Carlo Rubbia' => ['EUR', 'USD', 'AUD'],
        'Klaus von Klitzing' => ['EUR', 'USD', 'AUD'],
        'Gerd Binnig' => ['EUR', 'USD', 'AUD'],
        'Heinrich Rohrer' => ['EUR', 'GBP', 'AUD', 'RUR'],
        'Ernst Ruska' => ['EUR', 'USD', 'AUD'],
        'J. Georg Bednorz' => ['EUR', 'USD', 'GBP'],
        'Karl Alex Müller' => [],
        'Leon Max Lederman' => ['EUR', 'USD', 'GBP'],
        'Melvin Schwartz' => ['EUR', 'USD', 'GBP'],
        'Jack Steinberger' => ['EUR', 'USD', 'AUD'],
        'Hans Georg Dehmelt' => ['EUR', 'USD', 'AUD'],
        'Wolfgang Paul' => ['EUR', 'USD', 'AUD'],
        'Norman Foster Ramsey' => ['EUR', 'USD', 'AUD'],
        'Jerome Isaac Friedman' => ['EUR', 'USD', 'AUD', 'RUR'],
        'Henry Way Kendall' => [],
        'Richard E. Taylor' => ['EUR', 'USD', 'GBP'],
        'Pierre-Gilles de Gennes' => ['EUR', 'USD', 'AUD'],
        'Georges Charpak' => ['EUR', 'USD', 'AUD'],
        'Russell Alan Hulse' => ['EUR', 'USD', 'GBP'],
        'Joseph H. Taylor, Jr.' => ['EUR', 'USD', 'AUD', 'RUR'],
        'Bertram N. Brockhouse' => ['EUR', 'USD', 'AUD'],
        'Clifford G. Shull' => ['EUR', 'USD', 'GBP'],
        'Martin Lewis Perl' => ['EUR', 'USD', 'GBP'],
        'Frederick Reines' => ['EUR', 'USD', 'AUD'],
        'David M. Lee' => ['EUR', 'USD', 'AUD'],
        'Douglas D. Osheroff' => ['EUR', 'USD', 'AUD'],
        'Robert C. Richardson' => ['EUR', 'USD', 'AUD'],
        'Steven Chu' => ['EUR', 'USD', 'AUD'],
        'Claude Cohen-Tannoudji' => ['EUR', 'USD', 'AUD', 'RUR'],
        'William D. Phillips' => ['EUR', 'USD', 'AUD'],
        'Robert B. Laughlin' => ['EUR', 'USD', 'AUD'],
        'Horst L. Störmer' => ['EUR', 'USD', 'AUD'],
        'Daniel C. Tsui' => ['EUR', 'USD', 'AUD'],
        'Gerardus Hooft' => ['EUR', 'USD', 'AUD'],
        'Martinus J.G. Veltman' => ['EUR', 'USD', 'AUD'],
        'Zhores I. Alferov' => ['EUR', 'USD', 'AUD'],
        'Jack S. Kilby' => ['EUR', 'USD', 'AUD'],
        'Herbert Kroemer' => ['EUR', 'USD', 'AUD'],
        'Eric A. Cornell' => ['EUR', 'USD', 'AUD'],
        'Wolfgang Ketterle' => ['EUR', 'USD', 'AUD'],
        'Carl E. Wieman' => ['EUR', 'USD', 'AUD'],
        'Raymond Davis, Jr.' => ['EUR', 'USD', 'AUD'],
        'Riccardo Giacconi' => ['EUR', 'USD', 'AUD'],
        'Koshiba Masatoshi' => ['EUR', 'USD', 'AUD', 'RUR'],
        'Alexei A. Abrikosov' => ['EUR', 'USD', 'AUD'],
        'Vitaly L. Ginzburg' => ['EUR', 'USD', 'AUD'],
        'Anthony J. Leggett' => ['EUR', 'USD', 'AUD'],
        'David J. Gross' => ['EUR', 'USD', 'AUD'],
        'H. David Politzer' => ['EUR', 'USD', 'AUD', 'RUR'],
        'Frank Wilczek' => ['EUR', 'USD', 'AUD'],
        'Roy J. Glauber' => ['EUR', 'USD', 'GBP'],
        'John L. Hall' => ['EUR', 'USD', 'GBP'],
        'Theodor W. Hänsch' => ['EUR', 'USD', 'AUD'],
        'John C. Mather' => ['EUR', 'USD', 'AUD'],
        'George F. Smoot' => ['EUR', 'GBP', 'AUD'],
        'Albert Fert' => ['EUR', 'USD', 'AUD'],
        'Peter Grünberg' => ['EUR', 'USD', 'AUD'],
        'Kobayashi Makoto' => ['GBP', 'USD', 'AUD'],
        'Maskawa Toshihide' => ['EUR', 'USD', 'AUD'],
        'Yoichiro Nambu' => ['EUR', 'USD', 'AUD'],
        'Willard Boyle' => ['GBP', 'USD', 'AUD'],
        'Charles Kao' => ['EUR', 'USD', 'GBP'],
        'George E. Smith' => ['EUR', 'USD', 'AUD'],
        'Andre Geim' => ['EUR', 'USD', 'GBP'],
        'Konstantin Novoselov' => ['EUR', 'USD', 'GBP'],
        'Saul Perlmutter' => ['EUR', 'USD', 'AUD'],
        'Brian P. Schmidt' => ['EUR', 'USD', 'AUD'],
        'Adam G. Riess' => ['EUR', 'USD', 'AUD'],
        'Serge Haroche' => ['EUR', 'USD', 'AUD'],
        'David J. Wineland' => ['EUR', 'USD', 'AUD'],
        'François Englert' => ['EUR', 'USD', 'GBP'],
        'Peter Higgs' => ['EUR', 'USD', 'AUD'],
        'Akasaki Isamu' => ['EUR', 'USD', 'AUD'],
        'Amano Hiroshi' => ['EUR', 'USD', 'GBP'],
        'Shuji Nakamura' => ['EUR', 'USD', 'GBP'],
        'Kajita Takaaki' => ['EUR', 'USD', 'AUD'],
        'Arthur B. McDonald' => ['EUR', 'USD', 'AUD'],
        'David Thouless' => ['EUR', 'USD', 'AUD'],
        'Duncan Haldane' => ['EUR', 'USD', 'AUD'],
        'Michael Kosterlitz' => ['EUR', 'USD', 'AUD'],
        'Barry C. Barish' => ['EUR', 'USD', 'AUD'],
        'Kip S. Thorne' => ['EUR', 'USD', 'AUD'],
        'Rainer Weiss' => ['EUR', 'USD', 'AUD'],
        'Arthur Ashkin' => ['EUR', 'USD', 'GBP'],
        'Gérard Mourou' => ['EUR', 'USD', 'AUD'],
        'Donna Strickland' => ['EUR', 'USD', 'AUD'],
        'James Peebles' => ['EUR', 'USD', 'AUD'],
        'Michel Mayor' => ['EUR', 'USD', 'AUD'],
        'Didier Queloz' => ['EUR', 'USD', 'AUD'],
        'Reinhard Genzel' => ['EUR', 'USD', 'GBP'],
        'Andrea Ghez' => ['EUR', 'USD', 'AUD'],
        'Roger Penrose' => ['EUR', 'USD', 'AUD'],
        'Klaus Hasselmann' => ['EUR', 'USD', 'AUD'],
        'Manabe Syukuro' => ['EUR', 'USD', 'AUD'],
        'Giorgio Parisi' => ['EUR', 'USD', 'AUD'],
        'Alain Aspect' => ['EUR', 'USD', 'AUD'],
        'John F. Clauser' => ['EUR', 'USD', 'AUD'],
        'Anton Zeilinger' => ['EUR', 'USD', 'AUD'],
        'Pierre Agostini' => ['EUR', 'USD', 'AUD'],
        'Ferenc Krausz' => ['EUR', 'USD', 'AUD'],
        'Anne L\'Huillier' => ['EUR', 'USD', 'AUD'],
    ];

    public function load(ObjectManager $manager): void
    {
        foreach (self::ACCOUNTS as $clientName => $currencies) {
            $client = new Client();
            $client->setName($clientName);
            foreach ($currencies as $currency) {
                $account = new Account();
                $account->setCurrency($currency);
                $account->setAmount(0 == rand(0, 5) ? 0 : rand(0, 1000000));
                $client->addAccount($account);
            }
            $manager->persist($client);
        }
        $manager->flush();
    }
}
