version: "3.6"

services:
  db:
    container_name: "funds_transfer_db"
    restart: unless-stopped
    image: postgres:13.0-alpine
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: "GMT+2"
      PGTZ: "GMT+2"

  php:
    container_name: "funds_transfer"
    restart: unless-stopped
    image: funds_transfer
    depends_on:
      - db
    volumes:
      - "./app:/app/"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=pgsql://user:password@db/db
      - EXCHANGE_RATE_ACCESS_KEY=874ee5f710b4651907839ac809ca9c2f
      - EXCHANGE_RATE_CACHE_LIFE_TIME_SECONDS=3600

  nginx:
    container_name: "funds_transfer_nginx"
    restart: unless-stopped
    build:
      context: docker/nginx
    ports:
      - "8088:80"
    depends_on:
      - php

volumes:
  db:
